export const INCREASE_STEPPER='INCREASE_STEPPER';
export const DECREASE_STEPPER='DECREASE_STEPPER';

export const SAVE_RAW_DATA='SAVE_RAW_DATA';
export const SAVE_TABLE_DATA='SAVE_TABLE_DATA';
export const SAVE_CHART_CONFIG='SAVE_CHART_CONFIG';
export const SAVE_CHART_CONFIG_COLUMNS='SAVE_CHART_CONFIG_COLUMNS';